mmdeploy_dir: ../mmdeploy
mmseg_dir: ../mmsegmentation

quant_settings:
  dispatcher: pursus

calib:
  target_platform: TargetPlatform.TRT_INT8
  batch_size: 1
  input_height: 1024
  input_width: 2048
  device: cuda
  calib_steps: 32
  calibration_file: examples/data/Quant128FromTrainImages.txt
  calibration_h5file: examples/data/h5file/Quant128FromTrainImages.hdf5
  analysis:
    test_executor: False
    graphwise: True
    layerwise: True
    parameter: False
    variable: False
#    interested_outputs:
#      -

model:
  deploy_cfg: configs/mmseg/segmentation_tensorrt_static-1024x2048.py
  deploy_cfg_int8: configs/mmseg/segmentation_tensorrt-int8_static-1024x2048.py
  model_cfg: configs/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes.py
  checkpoint: ../mmdeploy_checkpoints/mmseg/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes_20200605_003338-2966598c.pth
  working_dir: ../work-dir/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/default
  onnx_file: ../work-dir/pspnet/pspnet_r50-d8_512x1024_40k_cityscapes/end2end.onnx
