
quant_settings:
  lsq_optimization: True                                      # 启动网络再训练过程，降低量化误差
  lsq_optimization_setting.steps: 500                         # 再训练步数，影响训练时间，500 步大概几分钟
  lsq_optimization_setting.collecting_device: cpu             # 缓存数据放在那，cuda 就是放在gpu，如果显存超了你就换成 'cpu'

data:
  calibration_file: examples/data/Quant32FromTrainImages.txt
  working_dir

model:
  deploy_cfg:
  deploy_cfg_int8:
  model_cfg:
  checkpoint:

pipeline:
  - torch2onnx:
      pass:pass
  - test_FP32:
      p:p
  - test_trt_int8:
      p:p
  - test_executor:
      p:p
  - test_ppq_int8:
      p:p



